SET			(AVEO_PATH				"${CMAKE_CURRENT_LIST_DIR}/../")
FIND_PATH	(AVEO_INCLUDE			"ve_offload.h"	PATHS "${AVEO_PATH}/include")
FIND_LIBRARY(AVEO_HOST_LIBRARY		"libaveoVH.so"	PATHS "${AVEO_PATH}/lib")
FIND_LIBRARY(AVEO_DEVICE_LIBRARY	"libaveoVE.so"	PATHS "${AVEO_PATH}/lib")
